name: Build and Test

on:
  push:
    branches: [main, dev]
    paths: ['Code/**', 'build-and-test.yml']
  pull_request:
    branches: [main, dev]
    paths: ['Code/**', 'build-and-test.yml']

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Light.GuardClauses.AllProjects.sln
    - name: Build Analyzer
      run: dotnet build ./Code/Light.GuardClauses.InternalRoslynAnalyzers/Light.GuardClauses.InternalRoslynAnalyzers.csproj -c Release --no-restore
    - name: Build
      run: dotnet build ./Code/Light.GuardClauses.AllProjects.sln -c Release --no-restore
    - name: Test
      run: dotnet test ./Code/Light.GuardClauses.Tests/Light.GuardClauses.Tests.csproj -c Release --no-build --verbosity normal
